// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ClaimExternalProbeProcedure from "../claim_external_probe_procedure";
import * as GenerateProbeProcedure from "../generate_probe_procedure";

export type ClaimExternalProbeArgs = __Infer<typeof ClaimExternalProbeProcedure.params>;
export type ClaimExternalProbeResult = __Infer<typeof ClaimExternalProbeProcedure.returnType>;
export type GenerateProbeArgs = __Infer<typeof GenerateProbeProcedure.params>;
export type GenerateProbeResult = __Infer<typeof GenerateProbeProcedure.returnType>;

