// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteExternalProbeReducer from "../complete_external_probe_reducer";
import ConfigureModelReducer from "../configure_model_reducer";
import EnqueueProbeReducer from "../enqueue_probe_reducer";
import GrantWorkerReducer from "../grant_worker_reducer";
import IngestObservationReducer from "../ingest_observation_reducer";
import MarkGapReducer from "../mark_gap_reducer";
import RevokeWorkerReducer from "../revoke_worker_reducer";

export type CompleteExternalProbeParams = __Infer<typeof CompleteExternalProbeReducer>;
export type ConfigureModelParams = __Infer<typeof ConfigureModelReducer>;
export type EnqueueProbeParams = __Infer<typeof EnqueueProbeReducer>;
export type GrantWorkerParams = __Infer<typeof GrantWorkerReducer>;
export type IngestObservationParams = __Infer<typeof IngestObservationReducer>;
export type MarkGapParams = __Infer<typeof MarkGapReducer>;
export type RevokeWorkerParams = __Infer<typeof RevokeWorkerReducer>;

