// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameKey: __t.string().primaryKey().name("game_key"),
  owner: __t.identity(),
  playerId: __t.string().name("player_id"),
  turn: __t.u32(),
  gameKind: __t.string().name("game_kind"),
  complete: __t.bool(),
  terminal: __t.bool(),
  outcome: __t.string(),
  eligibleResult: __t.bool().name("eligible_result"),
  basis: __t.string(),
});
