// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  owner: __t.identity(),
  playerId: __t.string().name("player_id"),
  gameKey: __t.string().name("game_key"),
  gameKind: __t.string().name("game_kind"),
  turn: __t.u32(),
  actor: __t.string(),
  advantage: __t.string(),
  basis: __t.string(),
  outcome: __t.string(),
  terminal: __t.bool(),
  reliable: __t.bool(),
  complete: __t.bool(),
  eligibleResult: __t.bool().name("eligible_result"),
  humanThreats: __t.byteArray().name("human_threats"),
  botThreats: __t.byteArray().name("bot_threats"),
  humanRemaining: __t.option(__t.u8()).name("human_remaining"),
  botRemaining: __t.option(__t.u8()).name("bot_remaining"),
  strokes: __t.u32(),
  senderFouled: __t.bool().name("sender_fouled"),
});
