// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  playerId: __t.string().name("player_id"),
  kind: __t.string(),
  text: __t.string(),
  memoryEpoch: __t.u64().name("memory_epoch"),
  prefRevision: __t.u64().name("pref_revision"),
  createdAt: __t.u64().name("created_at"),
  expiresAt: __t.u64().name("expires_at"),
  status: __t.string(),
  token: __t.u64(),
  leaseExpiresAt: __t.u64().name("lease_expires_at"),
  failures: __t.u32(),
  retryAt: __t.u64().name("retry_at"),
  bridgeMessageId: __t.string().name("bridge_message_id"),
});
