// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  owner: __t.identity(),
  playerId: __t.string().name("player_id"),
  intensity: __t.string(),
  unsolicited: __t.bool(),
  memes: __t.bool(),
  prefRevision: __t.u64().name("pref_revision"),
  memoryEpoch: __t.u64().name("memory_epoch"),
  clearedOrdinal: __t.u32().name("cleared_ordinal"),
  latestGameKey: __t.string().name("latest_game_key"),
});
