// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  playerId: __t.string().name("player_id"),
  gameKey: __t.string().name("game_key"),
  gameKind: __t.string().name("game_kind"),
  turn: __t.u32(),
  reason: __t.string(),
  model: __t.string(),
  personaVersion: __t.string().name("persona_version"),
  seed: __t.string(),
  expiresAt: __t.u64().name("expires_at"),
});
