// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  bucket: __t.string(),
  fileName: __t.string().name("file_name"),
  mime: __t.string(),
  size: __t.u32(),
  sha256: __t.string().name("sha_256"),
  enabled: __t.bool(),
  addedAt: __t.u64().name("added_at"),
});
