// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Administrator = __t.object("Administrator", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type Administrator = __Infer<typeof Administrator>;

export const CompletedResult = __t.object("CompletedResult", {
  gameKey: __t.string(),
  owner: __t.identity(),
  playerId: __t.string(),
  gameKind: __t.string(),
  ordinal: __t.u64(),
  outcome: __t.string(),
  valid: __t.bool(),
});
export type CompletedResult = __Infer<typeof CompletedResult>;

export const GenerationClaim = __t.object("GenerationClaim", {
  token: __t.u64(),
  expiresAt: __t.u64(),
  prompt: __t.string(),
  model: __t.string(),
  fallbackResponse: __t.string(),
});
export type GenerationClaim = __Infer<typeof GenerationClaim>;

export const GenerationLease = __t.object("GenerationLease", {
  id: __t.string(),
  token: __t.u64(),
  expiresAt: __t.u64(),
});
export type GenerationLease = __Infer<typeof GenerationLease>;

export const ModelConfig = __t.object("ModelConfig", {
  id: __t.u8(),
  url: __t.string(),
  model: __t.string(),
});
export type ModelConfig = __Infer<typeof ModelConfig>;

export const MyGames = __t.object("MyGames", {});
export type MyGames = __Infer<typeof MyGames>;

export const MyObservations = __t.object("MyObservations", {});
export type MyObservations = __Infer<typeof MyObservations>;

export const MyProbes = __t.object("MyProbes", {});
export type MyProbes = __Infer<typeof MyProbes>;

export const MyReactions = __t.object("MyReactions", {});
export type MyReactions = __Infer<typeof MyReactions>;

export const MyResults = __t.object("MyResults", {});
export type MyResults = __Infer<typeof MyResults>;

export const Observation = __t.object("Observation", {
  eventId: __t.string(),
  owner: __t.identity(),
  playerId: __t.string(),
  gameKey: __t.string(),
  gameKind: __t.string(),
  turn: __t.u32(),
  actor: __t.string(),
  advantage: __t.string(),
  basis: __t.string(),
  outcome: __t.string(),
  terminal: __t.bool(),
  reliable: __t.bool(),
  complete: __t.bool(),
  eligibleResult: __t.bool(),
  humanThreats: __t.byteArray(),
  botThreats: __t.byteArray(),
  humanRemaining: __t.option(__t.u8()),
  botRemaining: __t.option(__t.u8()),
  strokes: __t.u32(),
  senderFouled: __t.bool(),
});
export type Observation = __Infer<typeof Observation>;

export const ObservedGame = __t.object("ObservedGame", {
  gameKey: __t.string(),
  owner: __t.identity(),
  playerId: __t.string(),
  turn: __t.u32(),
  gameKind: __t.string(),
  complete: __t.bool(),
  terminal: __t.bool(),
  outcome: __t.string(),
  eligibleResult: __t.bool(),
  basis: __t.string(),
});
export type ObservedGame = __Infer<typeof ObservedGame>;

export const Reaction = __t.object("Reaction", {
  id: __t.string(),
  owner: __t.identity(),
  playerId: __t.string(),
  gameKey: __t.string(),
  gameKind: __t.string(),
  turn: __t.u32(),
  reason: __t.string(),
  model: __t.string(),
  personaVersion: __t.string(),
  seed: __t.string(),
  expiresAt: __t.u64(),
});
export type Reaction = __Infer<typeof Reaction>;

export const ReactionContext = __t.object("ReactionContext", {
  gameKey: __t.string(),
  advantage: __t.string(),
});
export type ReactionContext = __Infer<typeof ReactionContext>;

export const Relationship = __t.object("Relationship", {
  key: __t.string(),
  owner: __t.identity(),
  playerId: __t.string(),
  lastIssued: __t.u64(),
  recent: __t.array(__t.string()),
});
export type Relationship = __Infer<typeof Relationship>;

export const ReplyProbe = __t.object("ReplyProbe", {
  id: __t.string(),
  owner: __t.identity(),
  prompt: __t.string(),
  response: __t.string(),
  status: __t.string(),
});
export type ReplyProbe = __Infer<typeof ReplyProbe>;

export const StreamGap = __t.object("StreamGap", {
  eventId: __t.string(),
  owner: __t.identity(),
  reason: __t.string(),
});
export type StreamGap = __Infer<typeof StreamGap>;

export const Worker = __t.object("Worker", {
  identity: __t.identity(),
});
export type Worker = __Infer<typeof Worker>;

